name: generate_gitHub_profile_3d_stats

on:
 schedule:
   - cron: "0 18 * * *"
 workflow_dispatch:

jobs:
 generateProfileStats:
   runs-on: ubuntu-latest
   name: Generate GitHub Profile 3D Statistics
   steps:
     - uses: actions/checkout@v3
     - uses: yoshi389111/github-profile-3d-contrib@0.7.1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         USERNAME: ${{ github.repository_owner }}
     - name: Commit and Push Changes
       run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add -A .
         git commit -m "Generated 3D stats"
         git push